### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by Vild** [PowerNex/PowerNex#25]
STATUS: Can't implement try this implementation yet, because of server problems.

**Comment by wilzbach** [comment]
how about using Travis or CircleCI? It's free & easy to setup.

**Comment by Vild** [comment]
The current thing that is stopping this now was that my server didn't want to compile my toolchain into a docker image. This is something which I want to as soon as I have time.

**Comment by Vild** [comment]
Travis has been working for a while.
