### ISSUE TITLE
Booting idea

### ISSUE THREAD

**Issue by Vild** [PowerNex/PowerNex#33]
What about using a small 32bit->64bit loader that loads the kernel from the initrd.
This could fix a lot of problems with the current elf being a ELF64.
This could hopefully clean up a lot of stupid code.
This would make it possible to use the .debug\* sections from the elf file for printing out stacktraces.
This could also add support for module initializers.

A 10 out of 10 idea!

**Comment by 06needhamt** [comment]
👍

**Comment by docandrew** [comment]
What issues are you currently having with ELF64?

**Comment by Vild** [comment]
Not really problem with ELF64, it's more that I have a higher half kernel which lives at 0xFFFF_FFFF_8000_0000 and without the current hacks grubs tries to do a identity map and put the kernel at exact that place.
Which it shouldn't do, it should put the kernel at a low address and then map it to the higher half.
The description of this issue is probably a bit wrong.

**Comment by docandrew** [comment]
I'm by no means a GRUB, ELF or linker script expert, but based on your linker script it seems like GRUB is putting it where you are asking it to:

        //starts the text section at your higher half (multiboot struct + 0xFFFFFFFF80000000;)
	. += KERNEL_VMA;                

	.text ALIGN(0x1000) : AT(ADDR(.text) - KERNEL_VMA) {
		*(.text .text.*)
	}

        //etc...

I think if you put the .text section above the . += KERNEL_VMA line, GRUB will load your kernel down at 1M.

**Comment by Vild** [comment]
If I do that the code will except to be run at that place.

The linker script currently links to code to run in the higher half, and via these custom loading options to grub: https://github.com/Vild/PowerNex/blob/master/Kernel/src/Boot.S#L32 , it loads the kernel down low, and run the code there until I get my paging up and running.
If I where to remove these custom loading attributes in the multiboot header grub will error out with "out of memory".

So I either need a loader in between GRUB and PowerNex or I'll need to somehow be able to remap the kernel Live while it is running.

**Comment by Vild** [comment]
This has been done for a while (PowerD)
