### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by KoczurekK** [PowerNex/PowerNex#46]
Hi! I hope it's right place to share ideas. :)
Any chances for ARM (v7?) support in near future? It would be great.

**Comment by WebFreak001** [comment]
+1, I want to see PowerNex™ on Raspberry Pi!

**Comment by Vild** [comment]
This would be fun to have, but I don't have access to any ARM device and the current code structure is not mature enough to be able to support multiple platforms.

So maybe in the future.

**Comment by KoczurekK** [comment]
Okey, thanks for reply. :)

**Comment by brolaugh** [comment]
@Vild isn't basicly all smartphones arm based? :P

**Comment by Vild** [comment]
Yes, but I can't do osdev on a smartphone.

**Comment by M4GNV5** [comment]
> @Vild isn't basicly all smartphones arm based? :P

*aren't
*basically

> Yes, but I can't do osdev on a smartphone.

Can't qemu emulate arm though? I agree however that you should focus on implementing more stuff (harddrives, more syscalls, ...)

**Comment by Vild** [comment]
Closing as this is not a goal at this moment.
