### ISSUE TITLE
Move to LDC

### ISSUE THREAD

**Issue by Vild** [PowerNex/PowerNex#49]
Looks like LDC is much better with it's codegen and cleanup.
More test needs to be done before this will happen.
#29 is probably also required.

**Comment by M4GNV5** [comment]
"LDC" ?

**Comment by Vild** [comment]
A D compiler with LLVM as the backend.
https://wiki.dlang.org/Compilers

**Comment by WebFreak001** [comment]
???

could you please reference a commit or say if you planned otherwise?

**Comment by Vild** [comment]
I've decided that in the close future only DMD will be supported, as I don't want to begin to patch LLVM and maintain those patches.
Also LDC is often a bit behind from the DMD version which would have blocked me from using new features if LDC doesn't have them yet.

TL;DR It's better for the code and less external dependencies are better.
