### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Vild** [PowerNex/PowerNex#60]
- [x] Make a coding style document
- [x] Apply the coding style to the code

**Comment by aberba** [comment]
Keeping the curly brackets on the first line, as in the CodeStyle, can make code less readable since D makes used of \@properties a lot. I guess you prefer the current style but I came to understand why the official D style was so. Keeping it like the official also prevents re-learning a CodeStyle.

**Comment by Vild** [comment]
I don't understand why it would make the code less readable.
Could you give an example?

**Comment by Vild** [comment]
@aberba ping

**Comment by aberba** [comment]
Sorry for the delay, was away for a while;

```d
@safe nothrow @nogc override int countAttributes() immutable {
    // code here
}
```
VRS

```d
@safe nothrow @nogc override 
int countAttributes() immutable 
{
    // code here
    if (param < 0)
    {
        ...
    }
    else
    {
        ...
    }
}
```
D is more high-level with many language properties, the standard CodeStyle went with the second for a reason. First version can even be longer on a single line for templates. Makes comments and code really clear for long time maintenance and bug tracking.

**Comment by Vild** [comment]
Well I don't really agree that, and I wouldn't say that 
>[...] the standard CodeStyle went with the second for a reason. Makes comments and code really clear for long time maintenance and bug tracking.
is a argument why the have `{` on a separate line, I think it was more that the creators like that why of writing code.

(FYI: They don't have `@safe nothrow @nogc` etc. on a separate line like you wrote. For example: https://github.com/dlang/phobos/blob/master/std/stdio.d#L689-692 )

I don't really see a reason to have it on a separate line, I think it just wastes screen space.
Conclusion: I will not change what I have planned.

**Comment by WebFreak001** [comment]
when the line is longer than your max soft line length you want to have, those attributes should be put on a separate line imo

**Comment by aberba** [comment]
It takes screen space, yes. In exchange for clean code. See Linux kernel
code on GitHub.

**Comment by Vild** [comment]
My goal is to set a code style standard and then use it consistently.

And if you can't bring any objective reasons except "Gives clean code", which is super subjective, then there is no reason for you to post about these non existing issues.
