### ISSUE TITLE
Build fails on Ubuntu 16.04.1 [ libfl.so.2: invalid ELF header ]

### ISSUE THREAD

**Issue by VlasovRoman** [PowerNex/PowerNex#63]
While compiling i gets strange error:
<br />
<br />cc/bin/x86_64-powernex-ar: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libfl.so.2: invalid ELF header
<br /> 
<br />I have tried install package from Debian testing reps, but it not solved this problem.

**Comment by Vild** [comment]
What does `file  /usr/lib/x86_64-linux-gnu/libfl.so.2` output?

**Comment by M4GNV5** [comment]
i get the same.
i just replaced `cc/bin/x86_64-powernex-ar` inside the build file with `ar`
Afaik ar just packs files anyways so using the system one shouldnt be that big of a problem.

**Comment by M4GNV5** [comment]
also:
```
➜  ~ file /usr/lib/x86_64-linux-gnu/libfl.so.2    
/usr/lib/x86_64-linux-gnu/libfl.so.2: symbolic link to libfl.so.2.0.0
➜  ~ file /usr/lib/x86_64-linux-gnu/libfl.so.2.0.0
/usr/lib/x86_64-linux-gnu/libfl.so.2.0.0: ASCII text
➜  ~ cat /usr/lib/x86_64-linux-gnu/libfl.so.2.0.0
/* GNU ld script
 *                                -*- Mode: C -*-
 * libfl.so ---
 * Author           : Manoj Srivastava ( srivasta@golden-gryphon.com )
 * Created On       : Mon Sep 11 13:25:55 2006
 * Created On Node  : glaurung.internal.golden-gryphon.com
 * Last Modified By : Manoj Srivastava
 * Last Modified On : Tue Sep 12 03:34:30 2006
 * Last Machine Used: glaurung.internal.golden-gryphon.com
 * Update Count     : 2
 * Status           : Unknown, Use with caution!
 * HISTORY          :
 * Description      :
 *
 * GNU ld script
 * When shared linking is requested, map the request to the PIC static
 * library, which is the closest we come to a shared library here.
 *
 * arch-tag: ce35efb4-3893-42c7-bdcb-56d95beba2ac
 */

INPUT( /usr/lib/x86_64-linux-gnu/libfl_pic.a )
```

**Comment by VlasovRoman** [comment]
+, libfl.so* in Debain-like systems contain same information.

**Comment by Vild** [comment]
I guess I should setup a build server that builds the toolchain for multiple distros.
I'll add this to my TODO list.

(Do this at the same time as #25)

**Comment by Vild** [comment]
Superseeded by #55 & #80
