### ISSUE TITLE
toolchainManager.d fails at binutils:47%

### ISSUE THREAD

**Issue by AravK** [PowerNex/PowerNex#82]
DMD downloads okay but during the binutils download curl just breaks, saying that a partial file was transferred and failing horribly. I found the URL of the tar.gz and tried to download it manually (from Firefox) but it failed too. You might have to reupload it. I remember that a previous version worked fine.

**Comment by Vild** [comment]
You mean this one? https://ci.vild.io/job/PowerNex/job/powernex-binutils/job/master/8/artifact/powernex-binutils.tar.xz
Because it works for me...

**Comment by AravK** [comment]
Wget works fine. The toolchainManager error only occured when I was using
my school internet. With my home internet, toolchainManager works fine but
a manual curl command fails with the internal error below. Might have
missed an option, not sure why this is happening. When I was at school, I
would receive a partial transfer error. Don't have any more details.

>
-- 

AK

**Comment by Vild** [comment]
I'm closing this as I guess something was blocking the download on your school internet and without any details I can't really debug if the server is miss configured.
